### ISSUE TITLE
Move to embl-cba

### ISSUE THREAD

**Issue by tischi** [embl-cba/spindle3d#32]
@TobiasKletter 

Do you mind if I move the repo here?
https://github.com/embl-cba

Usually my policy is to move repos there upon publication.
Not sure why I did not do it for this one.
**The old link that we have in the publication would stay functional.** It would automatically be forwarded.

We may also ask JCB whether they could change the link in the online version of the publication.

**Comment by TobiasKletter** [comment]
Sure, no objections!

**Comment by tischi** [comment]
Done.
