### ISSUE TITLE
Improve README: 3D requirements

### ISSUE THREAD

**Issue by tischi** [embl-cba/spindle3d#34]
@TobiasKletter I think it would be necessary to add a screenshot (e.g., ImageJ Orthogonal Views) to the README, explaining the input data requirements are that _both_ the chromatin and tubulin signal **must not** contact the image boundary in 3D, i.e. also not at the bottom and top of the z-stack. We should say that this is required because otherwise one cannot measure the 3D shape correctly. What do you think?

**Comment by TobiasKletter** [comment]
Done!
