### ISSUE TITLE
Improve README: Add example images

### ISSUE THREAD

**Issue by tischi** [embl-cba/spindle3d#35]
@TobiasKletter we should also add the example images for download to the README!

**Comment by TobiasKletter** [comment]
Yes I was thinking the same!

**Comment by TobiasKletter** [comment]
Currently updating the README and I realised that the first thing we actually mention is that there is a command that let's you download the example images. I think it's fine like this?

**Comment by tischi** [comment]
Maybe, yes. But then we should stress more that people actually look at it!
And we should put orthogonal view screenshots of some of the example data.

**Comment by TobiasKletter** [comment]
OK, I added the following to the input requirements section: 
"Important: Spindle3D will abort the analysis if the objects (chromatin or spindle) are in direct contact with any of the image borders (also see 'Troubleshooting')."
and the orthogonal views can be found in the Troubleshooting

**Comment by tischi** [comment]
Awesome!!
